[project]
name = 'pump'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'

[[project.requirements]]
[contracts.mbot]
path = 'contracts/mbot.clar'
clarity_version = 3
epoch = 3.0

[contracts.mbot-trait]
path = 'contracts/mbot-trait.clar'
clarity_version = 3
epoch = 3.0

[contracts.pump-token]
path = 'contracts/pump-token.clar'
clarity_version = 3
epoch = 3.0

[contracts.pump-token-dex]
path = 'contracts/pump-token-dex.clar'
clarity_version = 3
epoch = 3.0

[contracts.sip-010-trait]
path = 'contracts/sip-010-trait.clar'
clarity_version = 3
epoch = 3.0
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
